name: task_manager1
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  email_validator: ^3.0.0
  flutter_svg: ^2.2.0
  pin_code_fields: ^8.0.1
  image_picker: ^1.1.2
  http: ^1.4.0
  shared_preferences: ^2.5.3
  get: ^4.7.2



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0



flutter:


  uses-material-design: true

  assets:
    - assets/images/